version: '3.8'

services:
  dashboard:
    build: .
    container_name: sentinel_dashboard
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - .:/app

  orchestrator:
    build: .
    container_name: sentinel_orchestrator
    command: python3 monitor.py
    env_file:
      - .env
    volumes:
      - .:/app